module.exports = `
<p class = "dark px30"> Elena Tarasova </p>
          <p class = "dark px14"> (piano) </p>
          <p class = "blue px14"> Winner of international competitions
            <br> Actor YNOFF Agence Art Consulting (France)
            <br> Member of the programs of the Moscow State Academic Philharmonic
            <br> Author of ideas and artistic director of a number of musical projects
            <br> Lecturer at the Tchaikovsky Moscow State Conservatory
            <br> Member of the World Piano Teachers Association
            <br> Member of the International Union of Musicians </p>

 <p> Elena Tarasova was born on May 16, 1984 in Moscow. She began studying music at the age of four. For eleven years, Elena's creative individuality was formed and developed in the class of Honored Teacher of the Russian Federation Olga Evgenievna Mechetina (Music School of the Academic Music School at the Moscow Conservatory, then the Academic Music School). During this time, Elena became a laureate of children's and youth competitions and festivals, a scholar of the Vladimir Spivakov International Charitable Foundation and the International Cultural Exchange Foundation (the Foundation’s president is Konstantin Orbelian), a soloist of the “Heritage” Association Philharmonic Society. </p>
<p> From 2002 to 2007, Elena is a <b> student of the Moscow Conservatory </b>. This is a happy time of creative searches and bright accomplishments under the leadership of great Masters - Professor, People’s Artist of Russia Sergey Leonidovich Dorensky and Professor, Honored Artist of the Russian Federation Pavel Tigranovich Nersesyan, People’s Artist of Russia, Professor Tigran Abramovich Alikhanov (class of the chamber ensemble), it is the object of the object, it will have the object to get the object, and it will have the object to get the object, and then it will have the object to get the object, and then it will have the object to get the object, and then it will have the object to get the object, it will have the object, it will have the object to get it) Margarita Ivanovna Kravchenko (class of accompanist art). After graduating from the conservatory with honors, Elena continued her studies in graduate school (2007 - 2010) in the class of Sergey Leonidovich Dorensky and Pavel Tigranovich Nersesyan. As part of postgraduate education, she additionally trained in the class of Tigran Abramovich Alikhanov and Margarita Ivanovna Kravchenko. </p>
  <h3> “Elena Tarasova is an excellent pianist. In recent years, she has grown into a serious actress. It has a delicate musicality and bright temperament. Constantly expanding its repertoire and often gives concerts. "
    <span> People’s Artist of the Russian Federation, Professor at the Moscow Conservatory,
Academician <p> C. L. Dorensky </p> </span> </h3>
  <p> Elena is the <b> laureate of international competitions </b>, among which are the 2nd Prize of the IV International Competition of Pianists. N. Rubinshtein (Paris, 1999), 1st prize of the contest “Classical Heritage. In memory of S. V. Rakhmaninov ”(Moscow, 2001), the 1st prize and the special Carla Judicha prize“ Premio Iacopo Napoli ”of the competition“ Citta di Morcone 2006 ”(Italy, 2006), victory in the WPTA International Piano Competition (Serbia, Novi - Garden, 2015). She is the holder of a diploma from the Mozarteum Summer Academy (Salzburg, Austria, 2003) and a Musical Spring at the Mill diploma (Moulin d'Ande, France, 2005). </p>

  <p> From 2007 to 2014 - the soloist of the Moscow Concert Philharmonic Association "Mosconcert". From 2006 to the present, Elena is a participant in the subscriptions and programs of the Moscow State Academic Philharmonic. From 2016 to the present - artist YNOFF Agence Art Consulting (France). </p>

  <p> Elena actively <b> gives concerts </b> with solo and symphonic programs in Moscow, in cities of Russia (the artist’s touring biography is more than sixty cities), also participates in international festivals abroad (France, Italy, Austria, Germany, Czech Republic, Japan). Elena was lucky to take part in the largest European projects, among which are the Radio France festival in Montpellier, the Lille National Orchestra festival, and the Les Pianos Folies festival.

  </p>
 <p> In May 2006, Elena Tarasova was honored to represent the Moscow Conservatory at the prestigious festival - Kyoto International Music Students Festival 2006 (Japan). In the autumn of the same year, as part of the Japan-Russia Exchange Concerts 2006 project, which was held from September 5 to October 20 in the form of a concert tour of fourteen cities in Japan, Elena acted not only as a soloist and ensemble, but also conducted several master classes. </p>

 <p> In the summer of 2012, in the Great Hall of the Moscow Conservatory, Elena recorded a demo-disc “The Acquisition of Time” (Bach-Busoni, Schubert-List, Liszt). The recordings of Elena’s concerts were repeatedly broadcast on Radio France, Orpheus Radio Station, and the Russian World Foundation radio station. </p>

<h3> “Pianist Elena Tarasova is distinguished not only by her dedication in the profession, but also by such qualities as honesty and sincerity towards others and herself. In her game, it is noticeable especially: there is no fuss, the desire to please and please the listener, and as a result of this - the mannerism and imitation of fashion - themselves are left far away, and the human nobility is harmoniously combined with performing nobility. Years of performing activity allowed Elena Tarasova to create an extensive repertoire, the main feature of which is not only the proximity of each individual work to the inner world of the artist, but its relevance and “universalness”. Whether the works of the Baroque era or the works of composers of the 20th century - they all give an idea of ​​the high taste of the performer and his ability to separate the unconditional valuable from the secondary and minor ... ".
    <span> Candidate of Art History S. GOLUBENKO, abstract to CD </span> </h3>

  <p> The pianist's performing skills were celebrated in such halls as the Big, Small, Rachmaninov Halls of the Moscow Conservatory; Hall of Church Councils of the Cathedral of Christ the Savior; Svetlanovsky, Chamber, Theater Halls of the Moscow International House of Music; Vrubel Hall of the Tretyakov Gallery; Le Corum (Montpellier), conservatory hall in Lille, Palace of Congresses (Le Touquet), France; Steinway-Haus (Düsseldorf), Ballsaal Altes Kurhaus Aachen (Aachen), Germany; Vinohrady People’s House (Mayakovsky Concert Hall) and the Bethlehem Chapel in Prague; Kioi Hall (Tokyo), NHK Osaka Hall (Osaka), Alti Hall and Kyoto Concert Hall (Kyoto), Shirakawa Hall (Nagoya), Tohoku Fukushi University, Music Palace "Keyaki Hall" (Sendai), etc. </p>

  <h3> “One should especially note the style of Elena Tarasova’s play, combining both softness and filigree technique, and the strength that allowed her to perfectly embody such various musical images ...” <p> </p>
    <span> Russian Musician newspaper </span> </h3>

  <p> Elena's repertoire covers the time period from the Baroque to the present. </p>

  <h3> “... Chopin, Liszt, Rachmaninov - this is the element of Lena, in which she owns all the many colors of piano colors. She has her own tuning system before going on stage. A detached glance, with inner ear, scrolls the program in my head ... A religious rite begins, during which nothing exists except for Music. This is the professionalism of the highest standard ... "
    <span> Musician Magazine </span> </h3>
  <h3> “A wonderful impression was left by Elena Tarasova’s careful, elegant carcass. The “roundness” of phrasing, the working out and meaningfulness of the details, the flawless small technique - all this along with the desire to “convey the image of the composition” rather than “build the image of a virtuoso soloist”. The quality is not so frequent among modern pianists, who often suffer from “sportiness”. At the same time, I wanted to find out in the future how this “image” would take shape at the pianist in concerts of other composers, completely different in their appearance: let's say, Brahms or Shostakovich ... "
    <span> Florestan magazine </span> </h3>
  <h3> “On April 15, 2006, a symphony concert dedicated to the 100th anniversary of the birth of D. D. Shostakovich was held in the Big Concert Hall of the Lenin Memorial in Ulyanovsk, which included the Concerto No. 1 for piano and orchestra performed by Moscow pianist Elena Tarasova. The concert became an undoubted event in the cultural life of the city. Elena Tarasova showed herself as a talented musician with impeccable professional background, an organic sensation and understanding of the composer’s style. High ensemble qualities of the performer, a sincere and genuine sense of copyright humor in music, brilliance and sparkling of the piano technique, as well as fiery emotionality along with artistic relaxedness and freedom of music playing ensured the great success of the young pianist in the concert. The audience and the orchestra warmly welcomed the performance of a clearly gifted and promising rising star, student of the Moscow State Conservatory Elena Tarasova. "<Span> Artistic Director and Principal Conductor of UlGASO, Honored Artist of Russia, Professor S. V. FERULYEV </span> </h3>
  <h3> “Elena Tarasova came to us for the first time. Her performance reminded me of a school playing the piano of such masters as Naum Shtarkman, Emil Gilels, who also performed in Arkhangelsk. And this means that the school of great pianists is alive, and we are witnesses to this ... ”. <Span> Honored Artist of the Russian Federation, artistic director of the Pomor Philharmonic L.SPIRANOVA </span> </h3>
<h3> “Very feminine, soft, pretty-looking Elena Tarasova played a rare sounding composition by Mozart - Ten Variations on a Theme from Pilgrims from Mecca by the comic opera by C. V. Gluck. The inexhaustible fantasy of the writer makes me dress in the most unthinkable outfits familiar melodies familiar to Mozart's contemporaries. Impeccable mastery, exquisite grace, subtle cunning, brilliant humor and sweet coquetry - Elena Tarasova’s generous gift is rewarded with deafening applause. "

  <h3> “The concerts with the participation of Elena with great success and with a full house were held on the most prestigious stages of the Czech Republic. We would like to note that it was she who received the hottest applause of the public and the most enthusiastic reviews after the concerts, including from her Czech colleagues, as well as music and concert producers. ”
    <span> "WORLD OF CULTURE", an autonomous non-profit organization supporting culture, creativity and education. </span> </h3>
  <h3> “The concerts were a great success. Elena Tarasova subtly and soulfully performed the solo works of Chopin, Rachmaninov, Liszt, and also proved to be a sensitive partner in the performance of chamber music for violin and piano. These performances delighted both the general public and highly skilled professionals in Germany and found an enthusiastic response in the press. ”
    <span> ALLA BLATOW KLAVIERSTUDIO, Germany. </span> </h3>

  <h3> “Elena Tarasova is a young bright pianist, she has excellent performance data, a bright creative personality. He shows great interest in ensemble music making, where he reveals himself as a sensitive partner. ”
    <span> Associate Professor at the Moscow Conservatory, soloist with MGAF K. V. RODIN </span> </h3>
  <p> <b> A rich concert life gave Elena the opportunity to co-create with many performers, </b> among which are the soloists of the MSAF Hayk Kazazyan (violin), Kirill Rodin (cello); official entertainer Steinway & amp; Sons Andrey Yaroshinsky (piano), laureates of international competitions Leonard Schreiber (violin; Belgium), Pavel Baransky (baritone), string quartet “Rusquartet”, and others. </p>

  <p> Elena performed with the Symphony Orchestra of the Moscow Conservatory, the State Symphony Orchestra of the Republic of Tatarstan, chamber and symphony orchestras of Russian cities. </p>
<hr>

  <h3> Projects </h3>
  <p> Elena is the author of ideas and artistic director of a number of youth music projects. Formation of concepts and carrying out similar projects full of fresh and original repertoire finds is an important component of her creative activity. Of the projects, the most ambitious at the moment are the festival “To the 110th anniversary of the birth of Francis Poulenc,” after which Elena was awarded the prize “Golden Lyre”. Female face of the year. The creative elite of Moscow ", as well as the Youth musical project" Russian Evenings ". </p>

  <p> <b> The festival “On the 110th anniversary of the birth of Francis Poulenc” </b> (December 25, 2008 - April 25, 2009) presented a series of monographic programs that allow the audience to be deeply and diversely acquainted with the works of Poulenc a series of concerts dedicated to the music of his contemporaries, which met another goal of the project - to recreate the musical atmosphere of the era in which the composer lived and worked.
    Elena acted as the author of the idea, the artistic director of the festival and performer. The co-organizers of the project were a musicologist, a student at the Moscow Conservatory Natalia Reneva and a teacher at the Moscow Conservatory, flutist Svyatoslav Golubenko. </p>
  <p> <b> The project was supported </b> by the Ministry of Culture of the Russian Federation, Moscow Conservatory, French Embassy in the Russian Federation, French Cultural Center, Classic XXI Publishing House. The project was supervised by the professor of the Moscow Conservatory TA Alikhanov (People's Artist of the Russian Federation, Professor), E.G. Sorokina (Honored Artist of the Russian Federation, Professor), M.I. Kravchenko (Honored Artist of the Russian Federation, Professor), EM Tsareva (Honored Artist of Russia, Doctor of Art History, Professor), V.P. Chinaev (professor, doctor of art history). The festival was attended by laureates of international competitions, recent graduates and graduate students of the Moscow Conservatory. The festival's programs and the interviews of the participants were broadcast on the main information partner of the project - Orfei radio station. </p>
  <h3> “The author of the idea and the head of the festival was a graduate student of the Moscow Conservatory Elena Tarasova - a concert pianist, who for the first time was at the head of a large-scale project. It was time for her to accept congratulations: no organizational difficulties prevented her from performing an impressive part of the programs, successfully manifesting herself in all forms of the profession ... "
    <span> PLANET BEAUTY Magazine. </span> </h3>

  <p> The significant cultural and educational youth projects of Elena include <b> the monograph concert “Evgeny Svetlanov - composer” </b> (June 8, 2010, Moscow). The concert was held as part of the First Slavic Art Forum “Golden Knight” / President of the Forum - Nikolay Burlyaev /, the program included music by Maestro Evgeny Svetlanov Fedorovich. </p>
  <a href="http://svetlanovconcert.com/" target="_blank"> Official site of the project </a>

  <h3> “My“ appearance ”in these projects as the author of the idea and leader is in no way connected with the desire to engage in management, producing. It’s just the idea of ​​a performer, who may have a tendency to form cultural and educational concepts - and an attempt to translate this idea ... ”.
    “I am interested in the possibility of bringing my concept to life. And the possibility of introducing a new touch into the cultural life of society. In addition, I receive sincere pleasure from creative communication with the performers participating in the project, each of whom I really appreciate. ”
    <span> From Elena TARASOVA's interview. </span> </h3>


<p> Another significant and large-scale project of Elena is <b> Youth musical project “Russian Evenings” </b> (January 2011 - August 2015). This multifaceted cultural and educational project, which united young musicians from Moscow and St. Petersburg, became a kind of cultural bridge aimed at developing and strengthening the youth creative dialogue between representatives of the performing schools of St. Petersburg and Moscow, founded in due time by brothers Anton and Nikolai Rubinstein. / p>

  <p> <b> The first youth music festival “Russian Evenings” </b> with the previous creative action “Cultural Bridge Moscow - St. Petersburg” was held in the concert halls of the two capitals in 2011 (January 9 - June 10) and confirmed declared status of a multi-faceted cultural and educational project that promotes the preservation of traditions and the dissemination of the national heritage of Russia. As part of a large-scale program cycle, the festival presented the best and opened little-known pages of the musical heritage of the great Russian composers, noted a number of anniversary dates for the concert season, and also introduced the music community to the work of young composers in Russia. </p>

  <p> The <b> Board of Trustees </b> of the project includes 19 well-known representatives of the art sphere, including the USSR People’s Artists V. Lanovoy, Yu. Solomin, R. Nahapetov, V. Minin; folk artists of the Russian Federation E. Vitorgan, T. Alikhanov, S. Slonimsky, V. Gerello; Honored Artists of the Russian Federation M. Kravchenko, P. Nersesyan. <b> The festival was attended by </b> young brilliant performers who successfully showed themselves at numerous international competitions, graduates of the Moscow and St. Petersburg Conservatories, soloists of concert organizations of the two capitals, as well as young composers who performed the premiere performances of their compositions. The main information partners of the project - the radio station "Orpheus" and the radio station of the Russian World Foundation - provided airtime for stories about the project, interviews of participants and broadcasts of concert recordings. </p>

  <p> <b> At the end of the first festival, the organizing committee approved the further development strategy of the project. </b> Preserving the previous priorities, the multi-faceted project “Russian Evenings” annually presents cycles of concerts and events meeting the goals of preserving the traditions and spreading the creative heritage of Russian cultural and art figures. , development of national music education, preservation of the traditions of enlightenment, as well as concert programs in support of significant events in the world of culture. Special prize “Russian evenings. The New Generation, conceived by the organizing committee as a program to support and help young musicians in their professional development, provides young artists with the opportunity to debut as part of the concert programs of the Russian Evenings project on a par with the main artistic composition. </p>
  <a href="http://www.russianevenings.com/" target="_blank"> Official project site </a>

  <p> Since 2016, Elena is the artistic director of the Opus Universum International Music Project. <b> The project “Opus Universum” </b> (lat. “opus universum” - “universal labor”, “universal creation”, “whole profession”) brings together performers, a phrase of the actor and theatrical Director Juozas Miltinis "Do not look for a new art, look for the eternal." Appeal to the eternal - and therefore always new - implies a deep spiritual search and courage of creative solutions; "Whole profession" is a way of life.
    The project participants are mainly young teachers of the Moscow Conservatory - its recent graduates, laureates of international competitions, combining active concert activities in Russia and abroad and teaching activities in Alma Mater. </p>
  <a href="http://www.opus-universum.com/" target="_blank"> Official project site </a>
  <br>
  <hr>

  <h3> Pedagogical activities, work in the jury </h3>
  <p> From 2010 to the present, Elena teaches at the Moscow Conservatory. He takes part in the work of the jury of competitions and festivals, conducts master classes in Russian cities and abroad. From 2015 to the present - a member of the World Piano Teachers Association. From 2016 to the present - a member of the International Union of Musicians. </p>

<hr>

  <h3> Education </h3>
  <p> In collaboration with Maria Bakun and Yekaterina Gogoleva, Elena prepared a series of educational radio programs specifically for the Russian World Foundation radio station (June 2011). This was the beginning of a fruitful collaboration with the radio station. In 2012, a new author’s cycle of the “Musical Faces” program was aired. Elena's educational program “Dmitry Shostakovich. Creativity in the context of time "was among the Golden Lectures of the" Russian World ". </p>

  <p> In June 2013, at the suggestion of the Guild of the Scribes of the Biblio-Globus Trading House, Elena held a meeting with an audience, the theme of which was the history of Russian music from 988 to the present day. This meeting-conversation was the impetus to the development and creation of a series of educational lectures on the history of Russian music. </p>


`

